#!/bin/bash

# keybind Menu key
keybind=62
xmodmap -e "keycode $keybind = Mode_switch NoSymbol NoSymbol NoSymbol Shift_R"

xmodmap -e "keycode   9 = Escape dead_tilde dead_grave dead_tilde grave asciitilde grave"
xmodmap -e "keycode  10 = 1 exclam F1 F1 exclamdown onesuperior exclamdown"
xmodmap -e "keycode  11 = 2 at F2 F2 twosuperior dead_doubleacute twosuperior"
xmodmap -e "keycode  12 = 3 numbersign F3 F3 threesuperior dead_macron threesuperior"
xmodmap -e "keycode  13 = 4 dollar F4 F4 currency sterling currency"
xmodmap -e "keycode  14 = 5 percent F5 F5 EuroSign dead_cedilla EuroSign"
xmodmap -e "keycode  15 = 6 dead_circumflex F6 F6 onequarter asciicircum onequarter"
xmodmap -e "keycode  16 = 7 ampersand F7 F7 onehalf dead_horn onehalf"
xmodmap -e "keycode  17 = 8 asterisk F8 F8 threequarters dead_ogonek threequarters"
xmodmap -e "keycode  18 = 9 parenleft F9 F9 leftsinglequotemark dead_breve"
xmodmap -e "keycode  19 = 0 parenright F10 F10 rightsinglequotemark dead_abovering rightsinglequotemark"
xmodmap -e "keycode  20 = minus underscore F11 F11 yen dead_belowdot yen"
xmodmap -e "keycode  21 = equal plus F12 F12 multiply division multiply"
xmodmap -e "keycode  25 = w W Up Up aring Aring aring"
xmodmap -e "keycode  34 = bracketleft braceleft Print Print guillemotleft leftdoublequotemark guillemotleft"
xmodmap -e "keycode  35 = bracketright braceright Pause Pause guillemotright rightdoublequotemark guillemotright"
xmodmap -e "keycode  38 = a A Left Left aacute Aacute aacute"
xmodmap -e "keycode  39 = s S Down Down ssharp section ssharp"
xmodmap -e "keycode  40 = d D Right Right eth ETH eth"
xmodmap -e "keycode  45 = k K Insert Insert oe OE oe"
xmodmap -e "keycode  46 = l L Home Home oslash Oslash oslash"
xmodmap -e "keycode  47 = semicolon colon Prior Prior paragraph degree paragraph"
xmodmap -e "keycode  48 = dead_acute dead_diaeresis Next Next apostrophe quotedbl apostrophe"
xmodmap -e "keycode  59 = comma less Delete Delete ccedilla Ccedilla ccedilla"
xmodmap -e "keycode  60 = period greater End End dead_abovedot dead_caron dead_abovedot"
xmodmap -e "keycode  61 = slash question Up Up questiondown dead_hook questiondown"
xmodmap -e "keycode 105 = Control_R NoSymbol Right Right"
xmodmap -e "keycode 108 = ISO_Level3_Shift NoSymbol Left Left"
xmodmap -e "keycode 135 = Menu NoSymbol Down Down"
